### PR TITLE
Fixes Heap-buffer-overflow READ in pcpp::cross_platform_memmem

### PR DESCRIPTION
**Pull request by sashashura**
Fixes Heap-buffer-overflow READ in pcpp::cross_platform_memmem:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=43408

The `haystackLen` for `cross_platform_memmem` call in `SipRequestFirstLine::parseVersion` is calculated as `m_SipRequest->getDataLen() - m_UriOffset`. However when `m_DataLen` is 4 and `m_UriOffset` is 5 it results in -1 which is converted into max uint64. This leads to memory read out of data buffer bounds.

### CODE REVIEW

**Comment by seladb** [comment]
@sashashura pre-commit fails because you have trailing whitespace...

**Comment by seladb** [comment]
@sashashura pre-commit fails because you have trailing whitespace...

**Comment by sashashura** [comment]
I'm not sure why it fails the android build. Let me know if I need to do something.

**Comment by seladb** [comment]
> I'm not sure why it fails the android build. Let me know if I need to do something.

Lately the Android builds on macOS tend to fail, I'm not sure why... I reran the failed jobs

**Review by seladb — APPROVED** [review]

**Pull request merged**
