### PR TITLE
Fixing offsets and checks. Fixes issue 543/542

### PR DESCRIPTION
**Pull request by amritanshujohri**

### CODE REVIEW

**Comment by amritanshujohri** [comment]
@seladb do let me know.

**Comment by seladb** [comment]
thanks @amritanshujohri ! I'll take a look and let you know

**Review by seladb — COMMENTED** [review]
Thank you so much for making the fix!

It'd be great if you can also:
- Fork this PR from the `dev` branch instead of `master` so I can merge it to `dev` first
- If you have pcap examples with packets that would expose these issues, can you please add them to the [fuzzing regression tests](https://github.com/seladb/PcapPlusPlus/tree/master/Tests/Fuzzers/RegressionTests/regression_samples)? The fuzzing test suite runs address sanitizer to discover these kinds of issues so it should fail before the fix and pass afterwards. This is a great way to make sure these bugs won't surface again in the future

**Comment by seladb** [comment]
@amritanshujohri have you had a chance to read my previous comment?

**Comment by seladb** [comment]
@amritanshujohri let me know what we should do with this PR

**Comment by amritanshujohri** [comment]
Closing this one

**Pull request closed without merging**
