### PR TITLE
Issue #602 - Fix makefile dependencies

### PR DESCRIPTION
**Pull request by seladb**

### CODE REVIEW

**Comment by seladb** [comment]
thanks @amirgon for the feedback!
Unfortunately I couldn't reproduce the issue you mentioned.
When I run `touch Packet++/header/EthLayer.h` and then `make libs` I get the same results as you, but if I run `make libs` again nothing is being re-built. Here is the output I see (running on Ubuntu 20.04, but I got similar results on Windows/MinGW):
```shell
seladb@ubunu2004:~/PcapPlusPlus$ touch Packet++/header/EthLayer.h 
seladb@ubunu2004:~/PcapPlusPlus$ make libs
==== Building target: Common++ ====
Finished successfully building: Common++.lib
 
Finished successfully building: Common++.debug
 
==== Building target: Packet++ ====
Building file: src/ArpLayer.cpp
Building file: src/VlanLayer.cpp
Building file: src/SllLayer.cpp
Building file: src/GreLayer.cpp
Building file: src/VxlanLayer.cpp
Building file: src/EthLayer.cpp
Building file: src/Packet.cpp
Building file: src/NullLoopbackLayer.cpp
Finished successfully building: Packet++
 
==== Building target: Pcap++ ====
Building file: src/NetworkUtils.cpp
Building file: src/RawSocketDevice.cpp
Finished successfully building: Pcap++
 
Finished successfully building PcapPlusPlus libs
 
seladb@ubunu2004:~/PcapPlusPlus$ make libs
==== Building target: Common++ ====
Finished successfully building: Common++.lib
 
Finished successfully building: Common++.debug
 
==== Building target: Packet++ ====
Finished successfully building: Packet++
 
==== Building target: Pcap++ ====
Finished successfully building: Pcap++
 
Finished successfully building PcapPlusPlus libs

```

**Comment by amirgon** [comment]
Debuggin this with `make -nd libs` I can see that:

```
...
   Considering target file `Obj/Packet.o'.
...
     Prerequisite `Obj/Packet.d' is newer than target `Obj/Packet.o'.
...
    Must remake target `Obj/Packet.o'.
Invoking recipe from Makefile:54 to update target `Obj/Packet.o'.
echo Building file: src/Packet.cpp
g++ -DLINUX -I"./src" -I"./header" -I"../Common++/header" -I"/root/rdmaip_root/rdmaip_sim/PcapPlusPlus/3rdParty/EndianPortable/include" -I"../3rdParty/hash-library" -I/usr/include/netinet -fPIC -O2 -g -Wall  -c -fmessage-length=0 -MMD -MP -MF "Obj/Packet.d" -MT "Obj/Packet.o" -o "Obj/Packet.o" "src/Packet.cpp"
    Successfully remade target file `Obj/Packet.o'.
```

It may be related to [this comment](http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/#post-59:~:text=In%20some%20cases%20it%E2%80%99s%20been%20reported,spurious%20rebuilds%20of%20the%20object%20file.) regarding spurious rebuilds, follows by an example for how to solve this (POSTCOMPILE).

**Comment by seladb** [comment]
thanks @amirgon ! I looked at the comment and managed to implement the fix they suggest using `POSTCOMPILE`.

However, there is a backward compatibility issue here. This solution requires `mv` and `touch` that are not natively available on Windows. Fortunately those commands are available in `MSYS` but in order to use them they should be defined in [`platform.mk.*`](https://github.com/seladb/PcapPlusPlus/tree/master/mk) as new variables `MV` and `TOUCH`. Now here is the problem: once I start using these variables in the `Makefile`, the build will fail for anyone who didn't run `configure-<OS>`. That means that if you have a working local copy of PcapPlusPlus and you pull the latest code (without running `configure-*`) the build will start failing until you run `configure-*` again.
I tried to make the `POSTCOMPILE` fix backward compatible but it's very difficult because it involves changing the file extension from `.d` to `.Td` (where `POSTCOMPILE` change it back to `.d`).

I can suggest a few options:
- Leave it as it is, meaning without `POSTCOMPILE`
- Split the fix into 2 phases: 
  1. Add these new variables `MV` and `TOUCH` in `platform.mk.*` now but NOT implement the `POSTCOMPILE` solution yet
  2. Add the `POSTCOMPILE` fix in a couple of months, hoping that most of the users already have a local copy of PcapPlusPlus that has these variables

Please let me know what you think.

**Comment by amirgon** [comment]
> once I start using these variables in the `Makefile`, the build will fail for anyone who didn't run `configure-<OS>`.

Do you have some release schedule or strategy?  
You can require users to run `configure-<OS>` after each major release, for example, assuming they are a few months apart.
The spurious rebuilds problem may be a little annoying but it's not critical so you can add the `POSTCOMPILE` later on your next major release and ask users to run `configure-<OS>` then.  

Correctly handling of  depfiles, on the other hand (as fixed in this PR), is important because it can cause wrong builds.

**Comment by seladb** [comment]
I'm targeting the next release during the next couple of months. I've added `mv` and `touch` commands to this PR and will add `POSTCOMPILE` after the next release.

**Pull request merged**
