### PR TITLE
SOME/IP protocol support

### PR DESCRIPTION
**Pull request by miketsukerman**
* Add SomeIpLayer class to process SOME/IP messages
* Add SomeIpSdLayer class to process SOME/IP SD messages
* Update README.md file
* Add sample SOME/IP pcapng trace for tests

Protocol specification
* https://www.autosar.org/fileadmin/user_upload/standards/foundation/1-0/AUTOSAR_PRS_SOMEIPProtocol.pdf
* https://www.autosar.org/fileadmin/user_upload/standards/foundation/1-2/AUTOSAR_PRS_SOMEIPServiceDiscoveryProtocol.pdf

### CODE REVIEW

**Comment by maruu** [comment]
Hi @miketsukerman 

great to see that someone else on this project is also working on implementing automotive protocols :-)
We are also currently in the midst of preparing our SOME/IP (incl. SD and TP) implementation for upstreaming to PcapPlusPlus.

I noticed that your current SOME/IP and SOME/IP SD implementation currently does not support crafting of the respective layers. Are you planning on adding this feature in the near future?

The solution that we are going to propose, which will consist of SOME/IP, SOME/IP-SD, and SOME/IP-TP, allows crafting, as well as parsing. We have used it already for some of our tests and have, of course, already found and fixed some bugs in it :-)

As soon as we have the PRs ready, I will link them here. Maybe you can take a look and let me know what you think about the implementation? Maybe we could even collaborate in order to make the implementation even better?

Thanks and all the best,
maruu

**Comment by miketsukerman** [comment]
Hi @maruu,

> Hi @miketsukerman
> 
> great to see that someone else on this project is also working on implementing automotive protocols :-) We are also currently in the midst of preparing our SOME/IP (incl. SD and TP) implementation for upstreaming to PcapPlusPlus.
> 
> I noticed that your current SOME/IP and SOME/IP SD implementation currently does not support crafting of the respective layers. Are you planning on adding this feature in the near future?

My plan was to do it iteratively. This is the first WIP MR to introduce basic support for SOME/IP and SOME/IP SD.  Then later on maybe, not necessarily me. Also, at the moment, I focused more on the UDP protocol. Do you have TCP support? 

Regarding the possibility to compose a SOME/IP packet, I would have one question. The header is of course quite easy to create, but what do you with a payload? Because, it might be serialized differently. 
 
> The solution that we are going to propose, which will consist of SOME/IP, SOME/IP-SD, and SOME/IP-TP, allows crafting, as well as parsing. We have used it already for some of our tests and have, of course, already found and fixed some bugs in it :-)

Great to hear! I have been using pcapplusplus with my preliminary SOME/IP  parser implementation to process huge ethernet traces, works very fast. Would be quite interesting to check how you detect SOME/IP messages. 

> As soon as we have the PRs ready, I will link them here. Maybe you can take a look and let me know what you think about the implementation? Maybe we could even collaborate in order to make the implementation even better?
> 
> Thanks and all the best, maruu

I am very much interested looking in your implementation. And for sure, If I can contribute somehow, either doing a review or making an implementation. All good. Let me know where I can have a look at your code. 

Best,
Michael

**Comment by maruu** [comment]
Hi @miketsukerman 

sorry for the late response, I was on vacation.

> My plan was to do it iteratively. This is the first WIP MR to introduce basic support for SOME/IP and SOME/IP SD. Then later on maybe, not necessarily me. Also, at the moment, I focused more on the UDP protocol. Do you have TCP support?

Yes, although we handled the reassembly in a separate component, external to PcapPlusPlus. We could discuss whether it would be helpful to integrate this into PcapPlusPlus.

> Regarding the possibility to compose a SOME/IP packet, I would have one question. The header is of course quite easy to create, but what do you with a payload? Because, it might be serialized differently.

You are completely correct. For serialization/de-serialization of the payload we use a separate component, because it is heavily dependent on configuration (e.g. the layout of the payload, datatypes etc) and we did not want to introduce such specifics to PcapPlusPlus.

> Great to hear! I have been using pcapplusplus with my preliminary SOME/IP parser implementation to process huge ethernet traces, works very fast. Would be quite interesting to check how you detect SOME/IP messages.

Currently our approach is port-based - We add the ports which are negotiated over SOME/IP-SD to a static port map, which we then check for each packet. As a fallback mechanism we also implemented a SOME/IP heuristic, but due to the runtime complexity we try to avoid it.
The static port map of course has the drawback that it does not reliably work if you use PcapPlusPlus on multiple network interfaces (i.e. separate communication/service discovery domains). I briefly discussed possible solutions  with @seladb a while back, but until now we have never gotten around to working on it (it also has not bitten us yet though.. :-))

> I am very much interested looking in your implementation. And for sure, If I can contribute somehow, either doing a review or making an implementation. All good. Let me know where I can have a look at your code.

Great to hear. I will post the link here as soon as we have the first PR ready. 

Thanks a lot,
Dominik

**Comment by maruu** [comment]
Hi Michael,

we have opened the PR with our SOME/IP implementation here: https://github.com/seladb/PcapPlusPlus/pull/895/files

We are going to focus on upstreaming SOME/IP-TP and SOME/IP-SD as well now.

Let me know what you think :-)

All the best,
Dominik

**Comment by miketsukerman** [comment]
> @miketsukerman @maruu if you prefer to discuss this over Slack please let me know. We have Slack workspace for PcapPlusPlus and I can send you an invite

Can't promise that I will participate actively there, but would be cool to join :)

**Comment by miketsukerman** [comment]
> Hi Michael,
> 
> we have opened the PR with our SOME/IP implementation here: https://github.com/seladb/PcapPlusPlus/pull/895/files
> 
> We are going to focus on upstreaming SOME/IP-TP and SOME/IP-SD as well now.
> 
> Let me know what you think :-)
> 
> All the best, Dominik

I am planning to take a look in the next several days. Sorry for late reply.

**Pull request closed without merging**
