### PR TITLE
Improvements in TcpReassembly (performance increased)

### PR DESCRIPTION
**Pull request by gx740**
1. The signatures of callback function have been changed because passing the arguments by value is useless and gives performance overhead.
2. The type of `TcpStreamData::m_Connection` has been changed from `ConnectionData` to `const ConnectionData*` to avoid data copying
3. The private method `TcpReassembly::prepareMissingDataMessage` has been replaced by the new static function which is optimized on speed (no dynamic memory allocation).

### CODE REVIEW

**Comment by seladb** [comment]
Have you measured the performance improvements of these changes? How significant are they?

**Comment by gx740** [comment]
No, I didn't. The changes made in this PR are easy to understand.

First, there are classes `IPv4Address` and `IPv6Address` of 58 and 68 bytes long accordingly and their constructors allocate the memory. So the copy operation for object of one of these classes is heavyweight.

We have the classes `ConnectionData` (its size is 40 bytes) and `TcpStreamData` (32 bytes long) which are being passed to the callback functions by value. Both of these use two pointers to `IPAddress` which, in fact, point to the objects of types `IPv4Address/IPv6Address`.
In other words, passing an object by value forces to:
- copy almost 200 bytes
- make two memory allocations

Changing the type of `TcpStreamData::m_Connection` pursues the same goal: avoid object's copying.

In fact, everything is much worse. Let's look into source code where the callback is called:
```
TcpStreamData streamData(tcpLayer->getLayerPayload() + newLength, tcpPayloadSize - newLength, tcpReassemblyData->connData);
streamData.setDeleteDataOnDestruction(false);
m_OnMessageReadyCallback(sideIndex, streamData, m_UserCookie);
```
We can see an object of type `ConnectionData` is being copied twice.

**Comment by seladb** [comment]
Thanks for your answers/

Regarding passing `TcpStreamData` by value - I did it on purpose so users can use their own copy of the object without being worried that its memory will get freed or object will be changed. Of course coping objects has a performance impact but in the same time it simplifies the interaction with the users. So it's a trade-off between performance and usability...

Regarding the change in `prepareMissingDataMessage()` - your solution is definitely more efficient, but a little bit more complex. I'm also not sure how much performance improvement this change contributes to the overall performance of the TCP reassembly module

**Comment by gx740** [comment]
> Regarding passing `TcpStreamData` by value - I did it on purpose so users can use their own copy of the object without being worried that its memory will get freed or object will be changed. Of course coping objects has a performance impact but in the same time it simplifies the interaction with the users. So it's a trade-off between performance and usability...

Even having the copy of `ConnectionData` in a callback function, the user is forced to copy it anyway. So the const reference is more appropriated in this case.

The same is true for `TcpStreamData`. In the most cases the member `m_Data` points to data in packet or fragment. The only case it points to newly allocated memory is when missing data is detected. What the user can do with it? Nothing except copying because the user should stick together the parts of certain stream to parse the next layer.

**Comment by gx740** [comment]
> Regarding the change in `prepareMissingDataMessage()` - your solution is definitely more efficient, but a little bit more complex. I'm also not sure how much performance improvement this change contributes to the overall performance of the TCP reassembly module

Changes have a little impact on overall performance and can be omitted.

**Comment by gx740** [comment]
If to implement my proposal we can simplify `class TcpStreamData` to the next structure:
```
struct TcpStreamData
{
  uint8_t* m_Data;
  size_t m_DataLen;
  ConnectionData& m_Connection;
}
```

Many source code lines will disappeared.

And following code:
```
// send new data to callback
if (m_OnMessageReadyCallback != NULL)
{
  // prepare missing data text
  std::string missingDataTextStr = prepareMissingDataMessage(missingDataLen);

  // add missing data text to the data that will be sent to the callback. This means that the data will look something like:
  // "[xx bytes missing]<original_data>"
  size_t dataWithMissingDataTextLen = missingDataTextStr.length() + curTcpFrag->dataLength;
  uint8_t* dataWithMissingDataText = new uint8_t[dataWithMissingDataTextLen];
  memcpy(dataWithMissingDataText, missingDataTextStr.c_str(), missingDataTextStr.length());
  memcpy(dataWithMissingDataText + missingDataTextStr.length(), curTcpFrag->data, curTcpFrag->dataLength);

  //TcpStreamData streamData(curTcpFrag->data, curTcpFrag->dataLength, tcpReassemblyData->connData);
  //streamData.setDeleteDataOnDestruction(false);
  TcpStreamData streamData(dataWithMissingDataText, dataWithMissingDataTextLen, tcpReassemblyData->connData);
  m_OnMessageReadyCallback(sideIndex, streamData, m_UserCookie);

  LOG_DEBUG("Found missing data on side %d: %d byte are missing. Sending the closest fragment which is in size %d + missing text message which size is %d",
    sideIndex, missingDataLen, (int)curTcpFrag->dataLength, (int)missingDataTextStr.length());
}
```
can be changed to:
```
// send new data to callback
if (m_OnMessageReadyCallback != NULL)
{
  // prepare missing data text
  std::string missingDataTextStr = prepareMissingDataMessage(missingDataLen);

  // add missing data text to the data that will be sent to the callback. This means that the data will look something like:
  // "[xx bytes missing]<original_data>"
  size_t dataWithMissingDataTextLen = missingDataTextStr.length() + curTcpFrag->dataLength;

//  === START OF CHANGES ===
  std::vector<uint8_t> dataWithMissingDataText;
  dataWithMissingDataText.reserve(dataWithMissingDataTextLen);

  const char *begin = missingDataTextStr.c_str(), *end = missingDataTextStr.c_str() + missingDataTextStr.length();
  std::copy(begin, end, std::back_inserter(dataWithMissingDataText));
  
  begin = curTcpFrag->data, end = curTcpFrag->data + curTcpFrag->dataLength;
  std::copy(begin, end, std::back_inserter(dataWithMissingDataText));
//  === END OF CHANGES ===

  //TcpStreamData streamData(curTcpFrag->data, curTcpFrag->dataLength, tcpReassemblyData->connData);
  //streamData.setDeleteDataOnDestruction(false);
  TcpStreamData streamData(&dataWithMissingDataText[0], dataWithMissingDataTextLen, tcpReassemblyData->connData);
  m_OnMessageReadyCallback(sideIndex, streamData, m_UserCookie);

  LOG_DEBUG("Found missing data on side %d: %d byte are missing. Sending the closest fragment which is in size %d + missing text message which size is %d",
    sideIndex, missingDataLen, (int)curTcpFrag->dataLength, (int)missingDataTextStr.length());
}
```

**Comment by gx740** [comment]
Or just to remove the allocated memory after `m_OnMessageReadyCallback` is completed.

**Comment by gx740** [comment]
An implementation with using of vector is exception safe

**Comment by seladb** [comment]
> Even having the copy of `ConnectionData` in a callback function, the user is forced to copy it anyway. So the const reference is more appropriated in this case.
> 
> The same is true for `TcpStreamData`. In the most cases the member m_Data points to data in packet or fragment. The only case it points to newly allocated memory is when missing data is detected. What the user can do with it? Nothing except copying because the user should stick together the parts of certain stream to parse the next layer.

Yes, I agree with you. Let's keep those changes

> >Regarding the change in prepareMissingDataMessage() - your solution is definitely more efficient, but a little bit more complex. I'm also not sure how much performance improvement this change contributes to the overall performance of the TCP reassembly module
> 
> Changes have a little impact on overall performance and can be omitted.

Can you please omit those changes?

> If to implement my proposal we can simplify class TcpStreamData to the next structure:
> 
> ```cpp
> struct TcpStreamData
> {
>   uint8_t* m_Data;
>   size_t m_DataLen;
>   ConnectionData& m_Connection;
> }
> ```
> 
> Many source code lines will disappeared.

Why do you think we should remove the part that deals with freeing the data memory?

**Comment by gx740** [comment]
The changes in `prepareMissingDataMessage` has been undone.

> Why do you think we should remove the part that deals with freeing the data memory?

The only reason is to reduce the source code and improve readability. Current implementation is exception-safe but has much unnecessary code. We have a standard container (`std::vector`) that can manage the memory. I have prepared the changes that use this approach in the latest commit. We should decide whether the old class stay unchanged or apply my changes.

**Pull request merged**
