### PR TITLE
Fix missing musl flag in platform.mk

### PR DESCRIPTION
**Pull request by dehmarc**
Related issue has been created #773

### CODE REVIEW

**Review by seladb — APPROVED** [review]

**Comment by clementperon** [comment]
@dehmarc could you add a Musl compilation in the CI or at least give me the instruction you do to build it with musl?

**Comment by seladb** [comment]
@dehmarc  @clementperon we should probably also add this flag to the documentation:
https://pcapplusplus.github.io/docs/install/build-source/linux
https://github.com/PcapPlusPlus/pcapplusplus.github.io/blob/master/docs/install/linux.md

I thought I did but apparently I forgot...

**Comment by dehmarc** [comment]
Do you prefer a native build in an alpine container (e.g. alpine:3.13) or cross crompile on ubuntu machine/image? 
Not sure what strategy you follow..

On a native alpine(=musl) build I required the following dependencies to be installed
`apk add git bash build-base libpcap-dev linux-headers`

other than that its just running
`configure-linux.sh --musl`
`make -j$(nproc)`

**Comment by dehmarc** [comment]
> @dehmarc @clementperon we should probably also add this flag to the documentation: https://pcapplusplus.github.io/docs/install/build-source/linux https://github.com/PcapPlusPlus/pcapplusplus.github.io/blob/master/docs/install/linux.md
> 
> I thought I did but apparently I forgot...

yes definately! I guess I just searched the whole repo to check if you provide flags for a musl-based build

**Comment by clementperon** [comment]
@dehmarc MUSL flag is just because there is no backtrace support on musl libc right?

what about installing libexecinfo on alpine? 

This can be easily detected by cmake with CHECK_INCLUDE_FILES()

**Comment by dehmarc** [comment]
Then libexecinfo would need to be linked in case of musl. But it looks like libexecinfo provides the missing symbols (just checked the symbols, I have not tested it though)

**Comment by seladb** [comment]
Backtrace is only needed for tests, so I wouldn't require users to install libexecinfo on musl just for that...
The flag is probably the easiest solution

**Pull request merged**
