### PR TITLE
Fix a memory leak in example

### PR DESCRIPTION
**Pull request by gx740**

### CODE REVIEW

**Comment by seladb** [comment]
All you added is `m_RecentConnsWithActivity` in `GlobalConfig` but you didn't use it anywhere... was it intentional?

**Comment by gx740** [comment]
I have added a destructor in which an object is destroyed

**Comment by gx740** [comment]
`m_RecentConnsWithActivity` is a pointer to dynamically allocated object that is never deleted therefore I have added a destructor.

**Comment by seladb** [comment]
Oops you're right, my bad... I'll merge the PR now

**Pull request merged**
