### PR TITLE
ci: github: save and restore ccache database

### PR DESCRIPTION
**Pull request by clementperon**
In order to speedup compilation save and restore ccache database

### CODE REVIEW

**Comment by tigercosmos** [comment]
cool! do you feel it faster?

**Comment by clementperon** [comment]
> cool! do you feel it faster?

You you can check it went from 3-4min to <1min

**Review by tigercosmos — APPROVED** [review]

**Comment by seladb** [comment]
@clementperon how does the compiler know to use ccache? Should we configure `CMake` with the ccache directory? 🤔

**Comment by clementperon** [comment]
> @clementperon how does the compiler know to use ccache? Should we configure `CMake` with the ccache directory? 🤔

Because we merged this :) 
https://github.com/seladb/PcapPlusPlus/pull/1492#issuecomment-2232113960

**Comment by tigercosmos** [comment]
@clementperon  Seems that there are conflicts. You may want to fix it.

**Comment by clementperon** [comment]
> > > @clementperon how does the compiler know to use ccache? Should we configure `CMake` with the ccache directory? 🤔
> > 
> > 
> > Because we merged this :) #1483
> 
> But how does `ccache` know to use the `${{ github.workspace }}/.ccache` directory to get the cached data? Is it the default directory?

Yes that's the default directory for Ccahe

**Comment by clementperon** [comment]
From the documentation: https://ccache.dev/manual/4.2.html#_location_of_the_primary_configuration_file

**Review by seladb — APPROVED** [review]

**Pull request merged**
