### PR TITLE
[IP addresses] performance improvements in TcpReassembly

### PR DESCRIPTION
**Pull request by gx740**
The mapped type of `TcpReassembly::ConnectionList` has changed from `TcpReassemblyData*` to `TcpReassemblyData`.

Notice the size of `TcpReassemblyData` has increased but in next PR I will decrease the size to previous value (the type of `numOfSides` and `prevSide` will be changed to `int8_t`).

### CODE REVIEW

**Comment by gx740** [comment]
Do you have time to merge this PR?

**Comment by seladb** [comment]
@gx740 I've just merged the IP address changes to `master` so the `ipaddr_refactor` branch is no longer relevant. Do you want to make these changes from `dev`?

**Comment by gx740** [comment]
Ok, I will prepare the changes

**Comment by gx740** [comment]
Фку нщг

**Comment by gx740** [comment]
What changes from `ipaddr_refactor` branch were merged into `dev/master`?

**Comment by seladb** [comment]
I took most of the changes in `IPAddress`, `IPv4Address` and `IPv6Address` and made the necessary changes in other parts of the code

**Pull request closed without merging**
