### PR TITLE
Use token for codecov uploads

### PR DESCRIPTION
**Pull request by egecetin**
Recently most uploads failed because of rate limiting. Using token should fix the issue.

https://docs.codecov.com/docs/adding-the-codecov-token

image

image

### CODE REVIEW

**Comment by tigercosmos** [comment]
I am wondering if the token is under the organization or person?

**Comment by egecetin** [comment]
@tigercosmos It should be under @seladb's account since the repo is under person account

**Comment by seladb** [comment]
Maybe that's the reason coverage went down from 80+% to 74%? 🤔

**Comment by egecetin** [comment]
@seladb Did you add token to repo with following instructions?

https://docs.codecov.com/docs/adding-the-codecov-token

It still says,
`[2024-05-24T06:40:41.530Z] ['verbose'] Passed token was 0 characters long`

**Comment by egecetin** [comment]
Maybe it can be caused because changes still in dev branch also if you add a token

**Comment by seladb** [comment]
> Maybe it can be caused because changes still in dev branch, if you add a token

I added the token just now:
image

**Pull request merged**
