### PR TITLE
Fix reassembly

### PR DESCRIPTION
**Pull request by silviucpp**
Fix for https://github.com/seladb/PcapPlusPlus/issues/280

### CODE REVIEW

**Comment by silviucpp** [comment]
I have no idea why github shows is forked from master. SmartGit shows me it's from dev

**Comment by seladb** [comment]
I'm not familiar with SmartGit, but after you fork PcapPlusPlus you should create a branch out of `dev`. That way when you create the PR it will be merged to `dev`

**Comment by seladb** [comment]
There is another PR pending on the same file (#283). Can you please change the PR to point to `dev` so I can merge it and unblock the other PR?

**Comment by silviucpp** [comment]
:)) Please try now. Seems you can change the base from github with one click..

**Pull request merged**
