### PR TITLE
Add setter for ip address (src/dst) for IPv6 layer

### PR DESCRIPTION
**Pull request by jafar75**
Adding 2 methods for setting ip address (src/dst)

### CODE REVIEW

**Comment by jafar75** [comment]
#638

**Review by seladb — COMMENTED** [review]
Do you think you can add tests to https://github.com/seladb/PcapPlusPlus/blob/master/Tests/Packet%2B%2BTest/Tests/IPv6Tests.cpp ?

**Comment by jafar75** [comment]
> Do you think you can add tests to https://github.com/seladb/PcapPlusPlus/blob/master/Tests/Packet%2B%2BTest/Tests/IPv6Tests.cpp ?

@seladb

**Comment by seladb** [comment]
@jafar75 I just noticed that the PR will be merged to `master`, can you please change it so it'll be merged to `dev`?

**Pull request merged**
