### PR TITLE
NULL to nullptr for some files

### PR DESCRIPTION
**Pull request by hpirlo**
I started to port pcap++ to c++11. this is the first commit!

### CODE REVIEW

**Comment by seladb** [comment]
@hpirlo thank you for opening this PR! I'm currently out and won't be able to review. Maybe @egecetin or @clementperon can review?

**Comment by clementperon** [comment]
Pcap++ is already built with C++11 standards.
I agree it's proper to change null to nullptr but if you do it use clang-tidy and add the check in the CI.
https://clang.llvm.org/extra/clang-tidy/checks/modernize/use-nullptr.html

**Review by seladb — APPROVED** [review]
I think it's ok to convert `NULL` to `nullptr` in phases. It's probably too early to add the `clang-tidy` check at this point until we finish converting everything

**Comment by egecetin** [comment]
There are still other `NULL`s on the source code. For example, in `Common++`  

https://github.com/hpirlo/PcapPlusPlus/blob/7eff9470821052f114d7fcee2f0c4c5ebcadaba4/Common%2B%2B/src/GeneralUtils.cpp#L82.

Do you think all the `NULL`s should be converted before merging or can this be accepted as a part of it?

**Comment by seladb** [comment]
@hpirlo a more extensive PR by @clementperon was already merged which converts all of `NULL` occurrences to `nullptr`: https://github.com/seladb/PcapPlusPlus/pull/1028

I think we can close this PR for now.

Thank you so much @hpirlo for contributing to this project 🙏 ❤️ and sorry for the slow response. If you're still interested in contributing we have a lot of open issues waiting for someone to work on them 😃

**Comment by hpirlo** [comment]
@seladb Surely I will contribute to other open issues. Thanks for your support :heart: :pray:

**Pull request closed without merging**
