### PR TITLE
Less Operator fix and multicast support

### PR DESCRIPTION
**Pull request by jaudibert-euronext**
As requested, a pull request is opened for  #609 and  #611.

### CODE REVIEW

**Comment by jaudibert-euronext** [comment]
Need to fix IPv6Address variables: must be initialized by constructor, not by '{...}'

**Comment by seladb** [comment]
Thanks for working on it!
Maybe we should split issues #609 and #611 into different PRs?

**Comment by jaudibert-euronext** [comment]
Hi, it's fine we'll just vars and push again 👌

**Comment by jaudibert-euronext** [comment]
Hi @seladb
Finally we submitted two PRs (#621, #622) but.. some unit tests failed 😓

**Pull request closed without merging**
