### PR TITLE
Add PAT

### PR DESCRIPTION
**Pull request by egecetin**
For triggering workflow actions automated PRs requires PAT (Mentioned [here](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs)). After merge all of the workflows should be triggered and coverage report should be fixed

### CODE REVIEW

**Comment by seladb** [comment]
> @seladb Just a reminder. Did you add PAT to repo secrets?

@egecetin I'm sorry, I didn't add a PAT yet. Does it need to be a secret with write access to the repo?
Any idea which permissions it needs?

image

**Comment by seladb** [comment]
@egecetin I'm not sure which of the permissions in the screenshot above is "repo scoped write access". Do you have any idea?

**Comment by egecetin** [comment]
@seladb I'm not sure too but only the public_repo should be enough I think. Check this https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps

**Comment by seladb** [comment]
@egecetin I created the token and put it in a new `PAT` secret, let me know if anything else is needed

**Pull request merged**
