### PR TITLE
Update release notes

### PR DESCRIPTION
**Pull request by seladb**
@clementperon @egecetin please let me know what you think

### CODE REVIEW

**Review by egecetin — APPROVED** [review]
Looks like typos disliked notice of fixing typos😁. I can add an ignore rule to typos for now if you want it.

**Comment by seladb** [comment]
> Looks like typos disliked notice of fixing typos😁. I can add an ignore rule to typos for now if you want it.

Yes, I'm trying to figure out if we can ignore those words just in `release_notes.txt`, do you know if it's possible?

**Comment by egecetin** [comment]
@seladb Inline ignoring is not possible I think (not checked recently if they had any update). We can add the old rule we removed with a notice like this,

```
# These identifiers below are coming from deprecated functions which is mentioned in cmake/package/READMEs/release_notes.txt
# They can be removed in next release (first release after v23.09) when the release notes are changed.
getMesageType = "getMesageType"
setMesageType = "setMesageType"
getExtensionsLenth = "getExtensionsLenth"
createHandhakeMessage = "createHandhakeMessage"
```

**Comment by seladb** [comment]
> @seladb Inline ignoring is not possible I think (not checked recently if they had any update). We can add the old rule to `typos-config.toml` we removed with a notice like this,
> 
> ```
> # These identifiers below are coming from deprecated functions which is mentioned in cmake/package/READMEs/release_notes.txt
> # They can be removed in next release (first release after v23.09) when the release notes are changed.
> getMesageType = "getMesageType"
> setMesageType = "setMesageType"
> getExtensionsLenth = "getExtensionsLenth"
> createHandhakeMessage = "createHandhakeMessage"
> ```

Ok sure 👍

**Comment by egecetin** [comment]
@seladb Commited the ignore rule with 51b7f93

**Review by clementperon — APPROVED** [review]

**Pull request merged**
