### PR TITLE
Remove unused includes

### PR DESCRIPTION
**Pull request by seladb**

### CODE REVIEW

**Comment by Dimi1010** [comment]
Just FYI, CI is failing because that all the headers like <cstring> only guarante to declare their contents within the `std` namespace, while the old c headers like <string.h> only guarantee to have their contents in the global namespace. So some functions might need adjustments to use the `std::` version.

**Comment by seladb** [comment]
> Just FYI, CI is failing because that all the headers like `<cstring>` only guarantee to declare their contents within the `std` namespace, while the old c headers like `<string.h>` only guarantee to have their contents in the global namespace. So some functions might need adjustments to use the `std::` version.

Yes, I'm still working on this PR 🙂

**Comment by egecetin** [comment]
@seladb What about also adding https://github.com/include-what-you-use/include-what-you-use after fix all of them. I don't have experience with it, but do you already know or use it?

**Review by tigercosmos — APPROVED** [review]
LGTM

**Comment by seladb** [comment]
> @seladb What about also adding https://github.com/include-what-you-use/include-what-you-use after fix all of them. I don't have experience with it, but do you already know or use it?

I've never used it, but I can look into it. Probably in a separate PR?

**Comment by egecetin** [comment]
@seladb Separate PR is better, I think. Because it might need additional config which will mix this PR.

**Pull request merged**
