### PR TITLE
switch from CentOS to RedHat Entreprise Linux

### PR DESCRIPTION
**Pull request by clementperon**

### CODE REVIEW

**Comment by egecetin** [comment]
This should be also updated,

https://github.com/seladb/PcapPlusPlus/blob/a48ff9219db24e81ac76cf2a11bab796da48652e/CMakeLists.txt#L380

**Comment by clementperon** [comment]
> This should also be updated,
> 
> https://github.com/seladb/PcapPlusPlus/blob/a48ff9219db24e81ac76cf2a11bab796da48652e/CMakeLists.txt#L380

unused for the moment

> This should also be updated,
> 
> https://github.com/seladb/PcapPlusPlus/blob/a48ff9219db24e81ac76cf2a11bab796da48652e/CMakeLists.txt#L380



> This should also be updated,
> 
> https://github.com/seladb/PcapPlusPlus/blob/a48ff9219db24e81ac76cf2a11bab796da48652e/CMakeLists.txt#L380

@egecetin for the moment this part of CMake is unused but I have added RHEL to not forget it.
Also we can keep "centos" just in case a guy try to package for centos on its machine

**Review by seladb — APPROVED** [review]
@clementperon we also need to update the documentation. I found a few places which need update:
- https://pcapplusplus.github.io/docs/next/install#github-release ([source](https://github.com/PcapPlusPlus/pcapplusplus.github.io/edit/master/docs/install/index.mdx))
- https://pcapplusplus.github.io/docs/next/platforms#-linux ([source](https://github.com/PcapPlusPlus/pcapplusplus.github.io/edit/master/docs/platforms.mdx))
- https://pcapplusplus.github.io/docs/next/quickstart#step-1---download-pcapplusplus ([source](https://github.com/PcapPlusPlus/pcapplusplus.github.io/edit/master/docs/quickstart.mdx))
-

**Comment by seladb** [comment]
> @clementperon we also need to update the documentation. I found a few places which need update:
> 
>     * https://pcapplusplus.github.io/docs/next/install#github-release ([source](https://github.com/PcapPlusPlus/pcapplusplus.github.io/edit/master/docs/install/index.mdx))
> 
>     * https://pcapplusplus.github.io/docs/next/platforms#-linux ([source](https://github.com/PcapPlusPlus/pcapplusplus.github.io/edit/master/docs/platforms.mdx))
> 
>     * https://pcapplusplus.github.io/docs/next/quickstart#step-1---download-pcapplusplus ([source](https://github.com/PcapPlusPlus/pcapplusplus.github.io/edit/master/docs/quickstart.mdx))

@clementperon I updated the documentation in this PR: https://github.com/PcapPlusPlus/pcapplusplus.github.io/pull/80

**Pull request merged**
