### PR TITLE
Fix misspellings

### PR DESCRIPTION
**Pull request by egecetin**

### CODE REVIEW

**Review by seladb — COMMENTED** [review]
Thank you @egecetin for finding these typos!
Please find 2 small comments inline.

Can you share which tool you used to find them?
Maybe we can add this tool to CI so typos can be prevented before a PR is merged? 🤔

**Comment by egecetin** [comment]
@seladb I used [codespell](https://github.com/codespell-project/codespell) and a pair of eyes 😁. If we prepare a good exception list of words it can be added to CI but the plain check of tool gives some wrong suggestions. I don't remember at the which files exactly but some examples

- hist
- FileTests

**Comment by seladb** [comment]
> @seladb I used [codespell](https://github.com/codespell-project/codespell) and a pair of eyes 😁. If we prepare a good exception list of words it can be added to CI but the plain check of tool gives some wrong suggestions. I don't remember at the which files exactly but some examples
> 
>   * hist
>   * FileTests

I believe we can prepare a list of exceptions, do you think it's going to take a long time to prepare it?

**Comment by egecetin** [comment]
No, not a lot. Only ~10 words is sufficient for current commit. I will work on it.

**Comment by seladb** [comment]
> No, not a lot. Only ~10 words is sufficient for current commit. I will work on it.

Sure, thank you!

Let's just fix these 2 small issues and merge?
- https://github.com/seladb/PcapPlusPlus/pull/821#discussion_r815533672
- https://github.com/seladb/PcapPlusPlus/pull/821#discussion_r815533657

**Review by seladb — APPROVED** [review]

**Pull request merged**
