### PR TITLE
ci: install latest npcap-oem

### PR DESCRIPTION
**Pull request by clementperon**
This USERNAME/Password is set for mingw but not for visual, also bump npcap to latest version

### CODE REVIEW

**Comment by clementperon** [comment]
@seladb looks like   ${{ secrets.NPCAP_USERNAME }} and ${{ secrets.NPCAP_PASSWORD }} are not defined correct ?

**Comment by seladb** [comment]
> @seladb looks like ${{ secrets.NPCAP_USERNAME }} and ${{ secrets.NPCAP_PASSWORD }} are not defined correct ?

What do you mean by not defined correct?

**Comment by clementperon** [comment]
It seems that these env variables are not defined. Jobs still download the non OEM version in the CI pipeline.

**Comment by seladb** [comment]
Yes, these variables aren't exposed to forks because they contain Npcap username and password for the OEM package that I'm not supposed to share. That's why forks are using the non-OEM version and only the main repo uses the OEM version as you can see here:
https://github.com/seladb/PcapPlusPlus/runs/4975418568?check_suite_focus=true#step:5:20

**Pull request merged**
