### PR TITLE
Use std::unordered_map instead of std::map

### PR DESCRIPTION
**Pull request by tigercosmos**
part of #977

changed `std::map` to `std::unordered_map`

there are a few cases that still keep using `std::map` due to the original intention usage of the `std::map` properties.

### CODE REVIEW

**Comment by tigercosmos** [comment]
@seladb  ready for review. the only failed case is the CI issue.

**Comment by tigercosmos** [comment]
@seladb  still happens, any idea?
image

**Comment by seladb** [comment]
@tigercosmos maybe you need to change the CirrusCI image to `freebsd-version: "13.2"`?
This is done in this PR: https://github.com/seladb/PcapPlusPlus/pull/1281

**Comment by tigercosmos** [comment]
@seladb  should be fine now.

**Review by seladb — APPROVED** [review]

**Comment by seladb** [comment]
Thank you @tigercosmos for working on this! I think we finally got rid of `std::map` 😄

**Pull request merged**
