### PR TITLE
Bug #611 : Less operator does not work correctly due to toInt method (byte order…

### PR DESCRIPTION
**Pull request by github-euronext**
Less operator does not work correctly due to toInt method (byte order reversed)

### CODE REVIEW

**Comment by seladb** [comment]
@github-euronext your observation is correct! As you pointed out `toInt()` returns the wrong result.
However there are about 50 places in the code that use this method, and many of them assume that `toInt()` returns the reversed result. What we need to do is go over them one by one and change it... That's why some of the tests are failing

**Comment by mmizi** [comment]
I think your second option can be acceptable. For me toInt() can return as well in a reversed byte order so that we do not break any code. There is no logical issue in returning a reversed order.

So, yes in my point of view we could correct only the operator<. So we go for the second option?

**Comment by seladb** [comment]
> So we go for the second option?

Sounds good to me! In the future we might tackle the issue with `toInt()`

**Comment by mmizi** [comment]
As requested, I repushed it with the correction only for the less operator. I've also changed the username and mail :) 

It looks like that all tests passed

**Pull request merged**
