### PR TITLE
Update DnsLayer.cpp

### PR DESCRIPTION
**Pull request by AlienX2001**
Fixing https://github.com/seladb/PcapPlusPlus/issues/893

### CODE REVIEW

**Comment by seladb** [comment]
@AlienX2001 can you add a test to [`DnsTests.cpp`](https://github.com/seladb/PcapPlusPlus/blob/master/Tests/Packet%2B%2BTest/Tests/DnsTests.cpp)?
- You can add a pcap file in [`PacketExamples`](https://github.com/seladb/PcapPlusPlus/tree/master/Tests/Packet%2B%2BTest/PacketExamples)
- Convert it to hex stream and put that file in the same folder
- Then you can write a quick test that verifies that NXDOMAIN is parsed correctly

**Comment by seladb** [comment]
Thanks! But you didn't write any test that uses this file :)

**Comment by AlienX2001** [comment]
I saw the code structure of the tests and i think i got the gist of it, but my pcap file has many packets and not just 1, and so does my .dat file, so how would I proceed with it?

**Comment by seladb** [comment]
> I saw the code structure of the tests and i think i got the gist of it, but my pcap file has many packets and not just 1, and so does my .dat file, so how would I proceed with it?

Each `.dat` file should contain just 1 packet, and I think 1 packet should be enough for this test. You can follow these steps:
- Take your pcap file, extract 1 NXDOMAIN packet and save it to a separate file
- Replace the current pcap file (that has many packets) with this one (that has only 1 packet)
- Open this 1-packet pcap file in Wireshark
- Select the packet and right click -> copy -> ...as a Hex stream
- Replace the existing content of the `.dat` file with the content of the packet
- Write a test that uses this packet from the `.dat` file

Please let me know if you have any questions.

image

**Comment by seladb** [comment]
BTW, instead of naming these files `test.pcap` and `test.dat` you can give them more meaningful names like `dns_nxdomain.pcap` and `dns_nxdomain.dat`

**Comment by seladb** [comment]
@AlienX2001 can you please rename `test.pcap` and `test.dat` to more meaningful names like `dns_nxdomain.pcap` and `dns_nxdomain.dat`? I think this would be the last comment and we can merge the PR after that

**Comment by AlienX2001** [comment]
Done

**Comment by AlienX2001** [comment]
And sorry for my inactivity on the PR, I had a deadline to catch up for my university

**Comment by seladb** [comment]
@AlienX2001 the test itself is not there anymore 😕 
I remember you added a test in [`DnsTests.cpp`](https://github.com/seladb/PcapPlusPlus/blob/master/Tests/Packet%2B%2BTest/Tests/DnsTests.cpp) but I don't see it anymore...

**Comment by AlienX2001** [comment]
Ohk, I dont really understand why is it breaking, The READ_FILE_AND_CREATE_PACKET macro read the dat and creates a packet right?, naming convetion is "rawpacket<the number passed>", I simply copy pasted that code from above test cases, but somehow its breaking in that line.

**Comment by egecetin** [comment]
Your test case should start with,

```
timeval time;
gettimeofday(&time, NULL);
```

**Comment by AlienX2001** [comment]
Ohk, It passed all the tests, but could you explain, why that piece of code was needed? Thanks

**Comment by egecetin** [comment]
@AlienX2001 Probably @seladb can explain better but,  `READ_FILE_AND_CREATE_PACKET` macro uses `pcpp::RawPacket` constructor which you can see below,

https://github.com/seladb/PcapPlusPlus/blob/b6fd30cd9e0fdd88b9f4d36e30a0bd7a7cc0b91a/Tests/Packet%2B%2BTest/Utils/TestUtils.h#L23-L25

and this constructor requires an input `timeval` called as time, you can find constructor here,

https://github.com/seladb/PcapPlusPlus/blob/b6fd30cd9e0fdd88b9f4d36e30a0bd7a7cc0b91a/Packet%2B%2B/header/RawPacket.h#L265-L276

therefore, compilation will fail if you do not define a `timeval time` value.

**Comment by AlienX2001** [comment]
I see, thanks @egecetin .
I also dont seem to understand why this 1 pre commit test is failing

**Pull request merged**
