### PR TITLE
Add move constructor/assignment operator for ConnectionData

### PR DESCRIPTION
**Pull request by NanXiao**

### CODE REVIEW

**Comment by gx740** [comment]
I suggest not to merge this PR because the IPAddress will be replaced by the new one and the compiler will generate these constructors.

**Comment by NanXiao** [comment]
> I suggest not to merge this PR because the IPAddress will be replaced by the new one and the compiler will generate these constructors.

@gx740 So `ConnectionData` won't have pointer members, i.e., `srcIP` and `dstIP`? Thanks!

**Comment by gx740** [comment]
Yes `srcIP` and `dstIP` will not be the pointers

**Comment by NanXiao** [comment]
@gx740 Got it, thanks!

**Comment by gx740** [comment]
Let's close this PR.

**Comment by seladb** [comment]
Should we close the PR?

**Comment by NanXiao** [comment]
@seladb Go ahead, thanks!

**Pull request closed without merging**
